#! /bin/bash
#
# Generate a password with a length based on the given argument
# then copies it to your clipboard
# example: secret 16

function check_dependencies(){
    xclip -version &> /dev/null
	if [ $? -ne 0 ]
	then
		echo "error: xclip not installed"
		exit 1	
	fi    
}

check_dependencies
openssl rand -base64 $1 | xclip -sel clip
echo "secret copied to clipboard"




